### ISSUE TITLE
0.4.16 timeline

### ISSUE THREAD

**Issue by joaogui1** [google-deepmind/dm-haiku#737]
Hi! Is there a specific timeline for doing a release specifically supporting 0.4.16? At the moment the latest release (0.0.9) doesn't work with it

**Comment by tomhennigan** [comment]
[Haiku 0.0.11](https://pypi.org/project/dm-haiku/0.0.11/) has just been released which supports the latest release of JAX.

**Comment by joaogui1** [comment]
Thanks!
